### ISSUE TITLE
Unable to send push anymore : APN Invalid Token

### ISSUE THREAD

**Issue by alchy58** [calcazar/react-native-push-notification-CE#21]
Hi,
First of all, thank you for the lib, very useful !

I have added react-native-push-notification-CE on an app in may. I store the token on server side so I can send push notification (using the Symfony Sly\NotificationPusher : https://github.com/Ph3nol/NotificationPusher).

All where functionnal and I receveid push at this moment so I moved on others features.

Today, I added Android push support who is working well.

My problem is that iOS notifications won't work anymore, APNS telling me that the token is invalid. The token seems to be correct, the library is able to get it. The APNS certificate is still valid until may 2019.

I tried to send a notification with NWPusher (https://github.com/noodlewerk/NWPusher) to test the token apart my server code by directly copy/past the token from onRegister() method of the library. The token is rejected too.

I can't find others Apple modification on APNS since may away this one : https://www.engadget.com/2018/06/04/ios-12-grouped-notifications/

I don't really know is react-native-push-notification-CE can be the problem but I open this ticket to have your point of view. Do you have any idea of why the tokens are rejected without any modifications on the code ?

Thanks a lot !

**Comment by GuillermoGuevara** [comment]
i have the same isuue, any update for this?

**Comment by alchy58** [comment]
Problem was a bad certificate finally
