### ISSUE TITLE
onNotification from killed app inconsistency Android

### ISSUE THREAD

**Issue by clfristoe** [calcazar/react-native-push-notification-CE#27]
When I'm opening the Android version of my app upon receiving a notification when the app is killed, I'm experiencing some inconsistency. onNotification is being triggered, and I can see the deeplink being printed out to the console, but the following code inside the handler is not being called unless I'm stepping through with a debugger. It seems as if only the first line in the onNotification handler is being called.

My onNotification handler:
`
onNotification: (notification => {`
`console.log('push sent: ' + notification.deeplink) //shows up consistently`
`alert('Push sent '+notification.deeplink) //only shows when stepping through debugger` `if(notification.deeplink) {`
`showMessages({...passProps, url: notification.deeplink})`
`}`
`}),`

**Comment by ammarRajabA** [comment]
Hi @clfristoe , did you manage to solve this?

**Comment by clfristoe** [comment]
I ended up going a different route with this.
