### ISSUE TITLE
PushNotificationIOS was split out from the core of React Native

### ISSUE THREAD

**Issue by vanyasem** [calcazar/react-native-push-notification-CE#32]
This library needs to migrate in order to retain functionality in the next react native version
https://github.com/react-native-community/react-native-push-notification-ios

**Comment by khrizt** [comment]
I've made a [PR](https://github.com/calcazar/react-native-push-notification-CE/pull/33) for this issue, @calcazar can you take a look?

**Comment by chris-griffin** [comment]
Was this closed by https://github.com/calcazar/react-native-push-notification-CE/pull/33?

**Comment by vanyasem** [comment]
I guess so :P
